config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews do
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurants = Restaurant.new
  end

  def create
    restaurant = Restaurant.new(restaurant_params)
    restaurant.save
    redirect_to restaurants_path
  end

  private

  def set_restaurants
    @restaurant = Restaurant.find(params[:id])
  end

  def task_params
    params.require(:restaurant).permit(:title, :details, :completed)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @reviews = Review.new
  end

  def create
    review = Review.new(restaurant_params)
    review.save
    redirect_to reviews_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Mes restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant_path(restaurant), class: 'pull-right btn btn-default' %>
<%= restaurant.name %></li>
    <% end %>
  <% end %>
<% end %>
</ul>

app/views/restaurants/show.html.erb
<h2>Restaurant</h2>
<%= link_to edit_restaurant_path, class: 'pull-right btn btn-default' do %>

<h3><%= @restaurant.name %></h3>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.category %></p>
<p><%= @restaurant.phone_number%></p>